FROM ubuntu
LABEL maintainer="Donets"
RUN apt update
RUN apt install qt5-qmake -y
RUN apt install cmake -y
RUN apt-get install qt5-default -y
RUN apt install build-essential -y
COPY . /home
WORKDIR /home/exam_Tech_prog_summer_2021
RUN qmake -makefile -o Makefile "Donets" myProgram.pro
RUN g++ -o main main.cpp triangle.h triangle.cpp
CMD ["./Exam_proj_QtLess"]